development:
  adapter: mysql
  database: malibu_development
  username: maly
  password: booboo
  host: 0.0.0.0

test:
  adapter: mysql
  database: malibu_test
  username: maly
  password: booboo
  host: 0.0.0.0

production:
  adapter: sqlserver
  mode: ADO
  database: HeliosBS
  security: trusted

odbc_inventory:
  adapter: odbc
  dsn: malibu_inventory-#{current_store.alias}
  emulate_booleans: true
  trace: false
