# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "account_setups", :force => true do |t|
  end

  create_table "admins", :force => true do |t|
    t.column "username",         :string
    t.column "friendly_name",    :string,   :limit => 50
    t.column "crypted_password", :string,   :limit => 40
    t.column "salt",             :string,   :limit => 40
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "activated_at",     :datetime
  end

  create_table "form_instances", :force => true do |t|
    t.column "form_type_id",       :integer
    t.column "form_data_id",       :integer
    t.column "form_data_type",     :string
    t.column "store_id",           :integer
    t.column "customer_id",        :integer
    t.column "user_id",            :integer
    t.column "status_number",      :integer,  :default => 1
    t.column "created_at",         :datetime
    t.column "submitted",          :boolean
    t.column "has_been_submitted", :boolean,  :default => false
  end

  create_table "form_types", :force => true do |t|
    t.column "friendly_name",            :string
    t.column "name",                     :string
    t.column "can_have_notes",           :boolean
    t.column "can_have_multiple_drafts", :boolean
  end

  create_table "handbook_acknowledgements", :force => true do |t|
    t.column "digital_signature_id",   :integer
    t.column "digital_signature_hash", :string
  end

  create_table "logs", :force => true do |t|
    t.column "created_at",  :datetime
    t.column "log_type",    :string
    t.column "data",        :string
    t.column "object_id",   :integer
    t.column "object_type", :string
    t.column "agent_id",    :integer
    t.column "agent_type",  :string
  end

  create_table "manager_reports", :force => true do |t|
    t.column "overview",                        :text
    t.column "actual_debit",                    :integer, :limit => 10
    t.column "number_of_tans",                  :integer
    t.column "total_sales",                     :integer, :limit => 10
    t.column "total_revenue",                   :integer, :limit => 10
    t.column "previous_year_sales",             :integer, :limit => 10
    t.column "previous_year_tans",              :integer
    t.column "goal_for_month",                  :integer, :limit => 10
    t.column "actual_vs_goal_diff_for_month",   :integer, :limit => 10
    t.column "action_plan_for_next_month",      :text
    t.column "meetings_training_agenda",        :text
    t.column "cash_error",                      :integer, :limit => 10
    t.column "payroll_percent_for_month",       :integer
    t.column "store_inspection_grade",          :integer
    t.column "employees",                       :string
    t.column "maintenance_requests",            :string
    t.column "suggestions",                     :text
    t.column "store_needs",                     :text
    t.column "inventory_items_error",           :string
    t.column "action_plan_to_correct_problems", :string
  end

  create_table "notes", :force => true do |t|
    t.column "form_instance_id", :integer
    t.column "author_type",      :string
    t.column "author_id",        :integer
    t.column "text",             :text
    t.column "created_at",       :datetime
    t.column "attachment",       :string
  end

  create_table "sales_reports", :force => true do |t|
    t.column "store_daily_sales",       :integer
    t.column "opening",                 :boolean
    t.column "store_goal",              :boolean
    t.column "total_revenue",           :integer
    t.column "daily_cleaning",          :boolean
    t.column "plus_minus_goal_for_day", :integer
    t.column "employee_names",          :string
    t.column "employee_sales",          :string
    t.column "employee_ppa",            :string
    t.column "employee_tans",           :string
    t.column "store_ppa",               :integer
    t.column "total_tans",              :integer
    t.column "cash_error",              :integer
  end

  create_table "stores", :force => true do |t|
    t.column "alias",          :string,   :limit => 25
    t.column "friendly_name",  :string,   :limit => 50
    t.column "address",        :string
    t.column "contact_person", :string,   :limit => 25
    t.column "telephone",      :string,   :limit => 20
    t.column "tax_id",         :string
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "form_type_ids",  :string,                 :default => "--- []\n\n"
  end

  create_table "users", :force => true do |t|
    t.column "username",             :string,   :limit => 25
    t.column "friendly_name",        :string,   :limit => 50
    t.column "store_id",             :integer
    t.column "crypted_password",     :string,   :limit => 40
    t.column "salt",                 :string,   :limit => 40
    t.column "encryption_key",       :binary
    t.column "status",               :string
    t.column "password_change_date", :string
    t.column "activated_at",         :datetime
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
    t.column "form_type_ids",        :string,                 :default => "--- []\n\n"
  end

end
